security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: plaintext

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: app_login
            # No need for `allow_anonymous` here, control access in access_control section

    access_control:
        # Allow public access to login, register, and session-test
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/session-test, roles: PUBLIC_ACCESS }

        # Define roles for specific routes
        #- { path: ^/admin, roles: ROLE_RH }
        #- { path: ^/employee, roles: ROLE_EMPLOYEE }
        #- { path: ^/candidat, roles: ROLE_CANDIDAT }

        # Allow authenticated users to access the home page and the root ("/")
        #- { path: ^/home, roles: IS_AUTHENTICATED_FULLY }
        #- { path: ^/, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            App\Entity\User: plaintext
